# Generated by Django 4.2.24 on 2025-09-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("US", "United States"),
                            ("UK", "United Kingdom"),
                            ("CA", "Canada"),
                            ("AU", "Australia"),
                            ("FR", "France"),
                            ("DE", "Germany"),
                            ("IN", "India"),
                            ("JP", "Japan"),
                            ("BR", "Brazil"),
                            ("MX", "Mexico"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
